-- AlterTable
ALTER TABLE `Employee` ADD COLUMN `alcohol` BOOLEAN NULL,
    ADD COLUMN `allergies` VARCHAR(191) NULL,
    ADD COLUMN `bloodPressure` VARCHAR(191) NULL,
    ADD COLUMN `bloodSugar` VARCHAR(191) NULL,
    ADD COLUMN `bmi` DOUBLE NULL,
    ADD COLUMN `cholesterol` VARCHAR(191) NULL,
    ADD COLUMN `chronicConditions` VARCHAR(191) NULL,
    ADD COLUMN `emergencyNotes` VARCHAR(191) NULL,
    ADD COLUMN `exerciseFrequency` VARCHAR(191) NULL,
    ADD COLUMN `healthIssues` JSON NULL,
    ADD COLUMN `height` DOUBLE NULL,
    ADD COLUMN `preEmploymentCheckDate` DATETIME(3) NULL,
    ADD COLUMN `preferredHospital` VARCHAR(191) NULL,
    ADD COLUMN `primaryPhysician` VARCHAR(191) NULL,
    ADD COLUMN `smoking` BOOLEAN NULL,
    ADD COLUMN `vaccinations` JSON NULL,
    ADD COLUMN `weight` DOUBLE NULL;
