-- AlterTable
ALTER TABLE `ManagerAppraisal` ADD COLUMN `attendanceComments` VARCHAR(191) NULL,
    ADD COLUMN `attendanceRating` DOUBLE NULL,
    ADD COLUMN `guestServiceComments` VARCHAR(191) NULL,
    ADD COLUMN `guestServiceRating` DOUBLE NULL,
    ADD COLUMN `independenceComments` VARCHAR(191) NULL,
    ADD COLUMN `independenceRating` DOUBLE NULL,
    ADD COLUMN `knowledgeOfJobComments` VARCHAR(191) NULL,
    ADD COLUMN `knowledgeOfJobRating` DOUBLE NULL,
    ADD COLUMN `leadershipComments` VARCHAR(191) NULL,
    ADD COLUMN `leadershipRating` DOUBLE NULL,
    ADD COLUMN `qualityOfWorkComments` VARCHAR(191) NULL,
    ADD COLUMN `qualityOfWorkRating` DOUBLE NULL,
    ADD COLUMN `recordsComments` VARCHAR(191) NULL,
    ADD COLUMN `recordsRating` DOUBLE NULL,
    ADD COLUMN `safetyComments` VARCHAR(191) NULL,
    ADD COLUMN `safetyRating` DOUBLE NULL,
    ADD COLUMN `teamworkComments` VARCHAR(191) NULL,
    ADD COLUMN `teamworkRating` DOUBLE NULL;
