-- AlterTable
ALTER TABLE `candidate` ADD COLUMN `address` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `interviewhrreview` ADD COLUMN `expectedDoj` DATETIME(3) NULL,
    ADD COLUMN `noticePeriod` INTEGER NULL;

-- AlterTable
ALTER TABLE `leaverequest` ADD COLUMN `hodDecidedAt` DATETIME(3) NULL,
    ADD COLUMN `hodDecision` ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
    ADD COLUMN `hodNote` VARCHAR(191) NULL,
    ADD COLUMN `hrDecidedAt` DATETIME(3) NULL,
    ADD COLUMN `hrDecision` ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
    ADD COLUMN `hrNote` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `permissionrequest` ADD COLUMN `hodDecidedAt` DATETIME(3) NULL,
    ADD COLUMN `hodDecision` ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
    ADD COLUMN `hodNote` VARCHAR(191) NULL,
    ADD COLUMN `hrDecidedAt` DATETIME(3) NULL,
    ADD COLUMN `hrDecision` ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
    ADD COLUMN `hrNote` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `wfhrequest` ADD COLUMN `hodDecidedAt` DATETIME(3) NULL,
    ADD COLUMN `hodDecision` ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
    ADD COLUMN `hodNote` VARCHAR(191) NULL,
    ADD COLUMN `hrDecidedAt` DATETIME(3) NULL,
    ADD COLUMN `hrDecision` ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
    ADD COLUMN `hrNote` VARCHAR(191) NULL;
