-- AlterTable
ALTER TABLE `Candidate` ADD COLUMN `address` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `InterviewHRReview` ADD COLUMN `expectedDoj` DATETIME(3) NULL,
    ADD COLUMN `noticePeriod` INTEGER NULL;

-- AlterTable
ALTER TABLE `LeaveRequest` ADD COLUMN `hodDecidedAt` DATETIME(3) NULL,
    ADD COLUMN `hodDecision` ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
    ADD COLUMN `hodNote` VARCHAR(191) NULL,
    ADD COLUMN `hrDecidedAt` DATETIME(3) NULL,
    ADD COLUMN `hrDecision` ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
    ADD COLUMN `hrNote` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `PermissionRequest` ADD COLUMN `hodDecidedAt` DATETIME(3) NULL,
    ADD COLUMN `hodDecision` ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
    ADD COLUMN `hodNote` VARCHAR(191) NULL,
    ADD COLUMN `hrDecidedAt` DATETIME(3) NULL,
    ADD COLUMN `hrDecision` ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
    ADD COLUMN `hrNote` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `WFHRequest` ADD COLUMN `hodDecidedAt` DATETIME(3) NULL,
    ADD COLUMN `hodDecision` ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
    ADD COLUMN `hodNote` VARCHAR(191) NULL,
    ADD COLUMN `hrDecidedAt` DATETIME(3) NULL,
    ADD COLUMN `hrDecision` ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
    ADD COLUMN `hrNote` VARCHAR(191) NULL;
