-- CreateTable
CREATE TABLE `ManpowerRequisition` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `jobId` INTEGER NOT NULL,
    `requestDate` DATETIME(3) NOT NULL,
    `designation` VARCHAR(191) NULL,
    `reasonType` VARCHAR(191) NOT NULL,
    `reasonDetails` VARCHAR(191) NULL,
    `vacancies` INTEGER NULL,
    `minExperience` INTEGER NULL,
    `maxExperience` INTEGER NULL,
    `skills` VARCHAR(191) NULL,
    `education` VARCHAR(191) NULL,
    `training` VARCHAR(191) NULL,
    `reasonBreakdown` JSON NULL,
    `eduSSC` BOOLEAN NULL,
    `eduDiploma` BOOLEAN NULL,
    `eduBachelor` BOOLEAN NULL,
    `eduMaster` BOOLEAN NULL,
    `eduOther` VARCHAR(191) NULL,
    `urgent` BOOLEAN NULL DEFAULT false,
    `duration` VARCHAR(191) NULL,
    `reportingTo` VARCHAR(191) NULL,
    `raisedBy` VARCHAR(191) NULL,
    `raisedBySign` VARCHAR(191) NULL,
    `raisedByDate` DATETIME(3) NULL,
    `raisedByComments` VARCHAR(191) NULL,
    `approvedByHoD` VARCHAR(191) NULL,
    `hodSign` VARCHAR(191) NULL,
    `approvedByHoDDate` DATETIME(3) NULL,
    `approvedByHoDComments` VARCHAR(191) NULL,
    `approvedBySMO` VARCHAR(191) NULL,
    `smoSign` VARCHAR(191) NULL,
    `approvedBySMODate` DATETIME(3) NULL,
    `approvedBySMOComments` VARCHAR(191) NULL,
    `receivedByHR` VARCHAR(191) NULL,
    `hrSign` VARCHAR(191) NULL,
    `receivedByHRDate` DATETIME(3) NULL,
    `receivedByHRComments` VARCHAR(191) NULL,
    `hrReferenceNo` VARCHAR(191) NULL,
    `salaryRange` VARCHAR(191) NULL,
    `source` VARCHAR(191) NULL,
    `actionTaken` VARCHAR(191) NULL,
    `closedOn` DATETIME(3) NULL,
    `hrRemarks` VARCHAR(191) NULL,
    `status` VARCHAR(191) NOT NULL DEFAULT 'PENDING',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `ManpowerRequisition_jobId_key`(`jobId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `ManpowerRequisition` ADD CONSTRAINT `ManpowerRequisition_jobId_fkey` FOREIGN KEY (`jobId`) REFERENCES `Job`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
