-- AlterTable
ALTER TABLE `evaluationtest` ADD COLUMN `activeFrom` DATETIME(3) NULL,
    ADD COLUMN `activeTo` DATETIME(3) NULL,
    ADD COLUMN `instructions` VARCHAR(191) NULL,
    ADD COLUMN `isPublished` BOOLEAN NULL DEFAULT false,
    ADD COLUMN `level` VARCHAR(191) NULL,
    ADD COLUMN `purpose` ENUM('HIRING', 'TRAINING', 'ASSESSMENT', 'OTHER') NULL,
    ADD COLUMN `randomization` ENUM('NONE', 'SHUFFLE_QUESTIONS', 'SHUFFLE_OPTIONS', 'BOTH') NULL DEFAULT 'NONE',
    ADD COLUMN `role` VARCHAR(191) NULL;
