-- AlterTable
ALTER TABLE `resignationrequest` ADD COLUMN `withdrawDecidedAt` DATETIME(3) NULL,
    ADD COLUMN `withdrawDecision` ENUM('PENDING', 'APPROVED', 'REJECTED') NULL,
    ADD COLUMN `withdrawRequestedAt` DATETIME(3) NULL,
    ADD COLUMN `withdrawStatusChangedBy` INTEGER NULL,
    MODIFY `status` ENUM('SUBMITTED', 'UNDER_REVIEW', 'ON_HOLD', 'APPROVED', 'REJECTED', 'WITHDRAWN', 'WITHDRAW_REQUESTED', 'CANCELLED', 'COMPLETED') NOT NULL DEFAULT 'SUBMITTED';
