-- AlterTable
ALTER TABLE `resignationrequest` MODIFY `status` ENUM('SUBMITTED', 'UNDER_REVIEW', 'ON_HOLD', 'APPROVED', 'REJECTED', 'WITHDRAWN', 'CANCELLED', 'COMPLETED') NOT NULL DEFAULT 'SUBMITTED';
